### ISSUE TITLE
Allow to download localised version from app store

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#103]
Manage play store locales to allow android language to determine the language on first installation.

**Comment by niccs** [comment]
@Jun As per my understanding,  while installing the app first time, it should check the default language of installed OS on phone and the same should be applied to the application. Currently, it takes english by default. Please confirm.

**Comment by jmatsushita** [comment]
That's correct, I would like the app to use the default OS language. I believe that currently it will take english by default.

**Comment by jmatsushita** [comment]
@niccs Hey sorry I didn't test this. Can I check with you that it was implemented?

**Comment by niccs** [comment]
@jmatsushita, yes this one was fixed.  You can test this.
