### ISSUE TITLE
Add PIN confirmation step

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#104]
When choosing (in the wizard) or changing (in the settings) the PIN there should be a traditional verification step before saving the changes.

**Comment by niccs** [comment]
@Jun -- Need more information on verification step-- Does this  mean, 

1) We need to add one more text box below the PIN box,  and user should enter the PIN two times to verify that they are same?
2) Or is this related to  verifying the valid input/length.(Right now only digits are allowed).

**Comment by jmatsushita** [comment]
Hi @niccs it is 1) that I meant with a second PIN entry field and an validation error if the entries are not the same. (both in the Wizard and the Settings screen).

**Comment by niccs** [comment]
@jmatsushita, In that case we also  need strings for the label , the validation error and the confirmation message.

**Comment by niccs** [comment]
@jmatsushita,
 
We need Strings corresponding to following text boxes.

1)Label of the confirm PIN text  box in various languages                          
2)Error message when pin is not matching in various languages
