### ISSUE TITLE
Lock screen problem during hardware trigger training

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#150]
During the hardware trigger training, it is likely that the user's lock screen will be involved. It should probably be better explained in the training wizard instructions.

**Comment by jimmylogan** [comment]
Yes  - agree we should insert something ahead of the training saying:

"Using the power button to activate the alarm may lock your screen. Just unlock your screen to continue setting up the app". 

I'm not sure exactly where it should go or what it should look like in appearance.
