### ISSUE TITLE
Correcting use of set-up, set up and setup across the app

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/PanicButton#166]
According to the logic of this article [here](http://www.future-perfect.co.uk/grammar-tip/is-it-setup-set-up-or-set-up/), we should make the following changes:

•	The green ‘Set-Up’ page on the introduction should be changed to ‘Set Up’.
•	The ‘Setup Alarm and Setup Disguise’ buttons on the introduction page should be changed to ‘Set Up Alarm’ and ‘Set Up Disguise’
•	On the ‘Setup contacts’ page, it should be ‘Set Up Contacts’ or else ‘Contacts Setup’.
•	‘Setup alert message’ page should become ‘Set Up Alert Message’
•	‘Setup Alert’ should become ‘Set Up Alarm’ [see #165]
•	‘Setup Disguise’ should become ‘Set Up Disguise’
•	[When it is active] ‘Panic Button is set-up and active’ should be ‘set up and active’

**Comment by jmatsushita** [comment]
Changed this and also use all lower case instead of capitalised titles. 9565458
