### ISSUE TITLE
Remove or simplify the Vibration Duration Settings under the ‘Advanced Settings’

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/PanicButton#173]
The Vibration Duration Settings are complicated and probably give too many options for the average user. It’s also not clear which part of the activation process they relate to.

I suggest removing these settings entirely, or putting this another page, ‘Advanced Trigger Options’ which can be selected from this page. It could also be simplified along the following lines:

- Users are given a range of options in terms of length (long/medium/ short) rather than a potential length in ms.

- The stages of the activation process that they relate to are more clearly spelt out (e.g. “Long Vibration - this will increase the length of the long buzz which confirms that alarm has been activated”).

- The outcomes of particular configurations are described and recommended (e.g. “Long Vibration – this will increase the length of the long buzz which confirms that alarm has been activated. Increasing the length of this is recommended where users are concerned about false triggers and want to be highly aware that the alarm is in the process of being activated. Decreasing its length will mean that the alarm can be triggered more rapidly and may be appropriate where a user feels particularly at risk”.

**Comment by niccs** [comment]
@jmatsushita , @jimmylogan ,

These settings were added temporarily to finalize the  short and long vibration duration.
Once finalized , I can remove them altogether. Please let me know, if  required to do so before  the 27th release.

**Comment by jimmylogan** [comment]
hi @niccs  - I think we should remove them. It might be something we think about bringing in again for future releases if we get feedback from our testings that this is something that users want but, for the time being, I think this provides a level of configuration beyond what most will need. 

Thanks!
