### ISSUE TITLE
‘Power Button Trigger’ should be moved down the options on the ‘Advanced Settings’ page

### ISSUE THREAD

**Issue by jimmylogan** [PanicInitiative/PanicButton#175]
This is the first option that is being given to the user to configure the trigger. However, this is the least preferable option in terms of limiting the app’s usefulness; it would be better to encourage them to try configuring the trigger in different ways as a way of addressing ‘false trigger’ incidents. 

I suggest we move the option to deactivate the power button trigger further down the menu (after the ‘REDO TRAINING’ option) in order that the user sees that there are other ways to address the issue.

**Comment by jmatsushita** [comment]
Moved to #80
