### ISSUE TITLE
Change UX of Trigger Settings

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#179]
The idea is to have 2 preconfigured trigger settings
 1/ (Default) 7 repeated presses
 2/ Extra confirmation press
 
And then have the current detailed/advanced settings only be available when the 3rd option (3/ Custom) is selected.

**Comment by niccs** [comment]
@jmatsushita , so this means, we will add one more page under Settings-- "Trigger Settings" with 3 options(and remove Advanced Settings from there)--

1/ (Default) 7 repeated presses
 2/ Extra confirmation press
3/ Custom

Please clarify more on these 3 options:

Are these button controls??

a) 1/ (Default) 7 repeated presses--  on pressing this --?? 
2/ Extra confirmation press-- existing confirmation press is one press, this button press will add one more? and not more than 2?
3/ Custom  -On selecting custom-- the user will be routed to Advanced settings page??

**Comment by jmatsushita** [comment]
I think the top 3 options should be a radio button. When option 1 or 2 are selected then any advanced option on the screen should be greyed out or even hidden. When option 3 (custom) is selected, then advanced options should be available (either ungreyed, or revealed).

My preference is to use an active/unactive (greyed/ungreyed) approach.

Note that with regards to making the "Power button trigger disabled" option go at the bottom of the screen as James requested, this will also only be available in custom mode. 

The "Redo Training" option should be activated any time a change is made (between the 3 main modes, or within parameters of the custom mode).
