### ISSUE TITLE
please move to gradle

### ISSUE THREAD

**Issue by emdete** [PanicInitiative/PanicButton#51]
gradle is the new build system recommended for android projects. compared to maven it's much nicer and not that much effort to learn. see http://www.gradle.org/ and http://tools.android.com/tech-docs/new-build-system/user-guide . it even solves a problem i currently have with maven as i have version 3.0.5 and 3.1.1 is required - gradle always uses the correct version.

**Comment by jmatsushita** [comment]
@niccs Wondering if we can consider that the gradle migration is done?
