### ISSUE TITLE
Alert testing timeout message reappears.

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#83]
When letting the alert time out in the wizard, sometimes the message of failure will continue to reappear even after succeeding the next time.

**Comment by jmatsushita** [comment]
This is difficult to reproduce.

**Comment by niccs** [comment]
As per my understanding, the issue appears, in SETUP process when we configure the Alarm test.---I have tried reproducing this by re-installing the app many times, but not able to re-produce it.
@ Jun, is there some specific phone model, where this happens? 
Right now, not able to trace anything specific to this issue.

**Comment by jmatsushita** [comment]
Thanks for trying @niccs I'm closing this as "cannot reproduce" and removing from the "current" state.
