### ISSUE TITLE
On LG G3 when app closing it goes to a special phone menu screen 

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/PanicButton#84]
When the app is activated, the screen defaults to a phone menu that is not the main home screen (this is on an LG G3). not the end of the world but slightly confusing for the user.

**Comment by jmatsushita** [comment]
Not sure about reproducing this either.

**Comment by niccs** [comment]
This one again looks like hardware specific. It can be a case of customized android implementation by different vendors (in this case LG).  Please share your view points, how to proceed with this issue.

**Comment by jmatsushita** [comment]
I'll also close this and mark as cannot reproduce. If we have more such problems we can reopen and reference them here and try to work out when they occur.
